### PR TITLE
feat: expose global `recomputeAllPoppers` helper

### PR DESCRIPTION
**Pull request by antfu**
Currently, Floating Vue is already calling this function on the window `resize` event. While in some cases, user might want to trigger this manually in cases like tab switch or the others.

For example https://twoslash.netlify.app/refs/notations, when you click the `Input Code` on the first tab group, you will see the popup still persist.

### CODE REVIEW

**Comment by Akryum** [comment]
I'm not sure I understand the link between the issue and `recomputeAllPoppers`. Would the correct behavior be to hide the popper?

**Comment by antfu** [comment]
Current behavior:

https://github.com/Akryum/floating-vue/assets/11247099/99da265f-f169-42b4-b9d5-31ae9afa29ec

Expected behavior:

https://github.com/Akryum/floating-vue/assets/11247099/62d19842-f094-4471-97aa-d5145753eb27

This PR itself does not fix the issue but adds the capability of it. Users could add the call to `recomputeAllPoppers` on tab switch.

**Comment by antfu** [comment]
A temporary workaround we have: https://github.com/twoslashes/twoslash/commit/0e8cecae215ffe43af989e394d44b447f4e25a32

**Comment by Akryum** [comment]
Wouldn't it be better to observe visibility on target?

**Comment by antfu** [comment]
> Wouldn't it be better to observe visibility on target?

That would do, are you ok with enabling it by default for listening to every element?

**Pull request merged**
