### PR TITLE
feat(nuxt): add nuxt module

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
In nuxt.config.js

```js
{
  modules: [
    'v-tooltip/nuxt'
  ]
}
```

### CODE REVIEW

**Comment by hmaesta** [comment]
Why this –simple but extremely useful– PR wasn't merged yet? 😖

**Comment by Spunkie** [comment]
Can we please get this moving? @Akryum

**Comment by luizfeer** [comment]
Merge pls

**Comment by productfrontenddeveloper** [comment]
merge please

**Comment by RomainMazB** [comment]
Ping @Akryum

**Comment by apgapg** [comment]
As PR repository has been deleted. I have created a nuxt module for my usage:

https://github.com/apgapg/v-tooltip-nuxt

You can use this module till the official release.

**Pull request closed without merging**
